services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-app-php
    
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: desafio-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - app
      - mysql

  mysql:
    image: mysql:8.0
    container_name: desafio-mysql
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE:    desafio_dev
      MYSQL_USER:        sail
      MYSQL_PASSWORD:    password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data_mysql:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: desafio-redis
    ports:
      - "6379:6379"
    volumes:
      - db_data_redis:/data
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: desafio-mongodb
    ports:
      - "27017:27017"
    volumes:
      - db_data_mongodb:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data_mysql:
  db_data_redis:
  db_data_mongodb:
